<?xml version="1.0" encoding="UTF-8"?>
<testsuite time="46.04948878288269" tests='3' skipped='0'
name="Test_Rol_All" failures='2' errors='0'><testcase time="15.579362154006958" name="Login_With_Different_Roles_--_@1.1_" status="passed"
         classname="Test_Rol_All" >
            <system-out>
            <![CDATA[
            @scenario.begin
                @Test_Rol_All_1   @smoke_Test   @Test_Rol_All
                scenario: Login with different roles -- @1.1 
e                given I am on the login page ... passed in 1.069s 
                when I enter development@identidadtech.com and Identidad123* ... passed in 2.622s 
                when I click the &#34;Next&#34; button ... passed in 1.281s 
                when I should be logged in successfully ... passed in 6.491s 
                when I should see my development@identidadtech.com and Admin displayed on the screen ... passed in 4.116s 
@scenario.end
            ----------------------------------------------------------------------------------------------------
            ]]>
            </system-out>
        </testcase><testcase time="15.541069984436035" name="Login_With_Different_Roles_--_@1.2_" status="failed"
         classname="Test_Rol_All" >
            <failure message="'global_functions' object has no attribute 'evidence_path'" type="AssertionError">
                    <![CDATA[ Failing step: when I should see my cbarbosa@identidadtech.com and CompanyAdmin displayed on the screen ... failed in 4.091s  Location:4
                        {'step_type': 'when', 'name': 'I should see my cbarbosa@identidadtech.com and CompanyAdmin displayed on the screen', 'text': 'None', 'status': 'failed', 'duration': 4.091497182846069, 'error_msg': "'global_functions' object has no attribute 'evidence_path'", 'error_lines': ['  File "/usr/local/lib/python3.8/dist-packages/behave/model.py", line 1329, in run\n    match.run(runner.context)\n', '  File "/usr/local/lib/python3.8/dist-packages/behave/matchers.py", line 98, in run\n    self.func(context, *args, **kwargs)\n', '  File "steps/test_rol_step.py", line 38, in test_step_impl\n    context.menu_page.verify_rol_page(rol_esperado)\n', '  File "/home/fpalencia/Automations/mientorno/test-pruebas-automatizadas/Project/tests/pages/menu_page.py", line 115, in verify_rol_page\n    self.action.attach_screenshot_to_report()\n', '  File "/home/fpalencia/Automations/mientorno/test-pruebas-automatizadas/Project/tests/pages/global_functions.py", line 184, in attach_screenshot_to_report\n    screenshot_path = os.path.join(self.evidence_path, f"{name}.png")\n'], 'hash': 89462523, 'index': 4}
                    ]]>
                </failure><system-out>
            <![CDATA[
            @scenario.begin
                @Test_Rol_All_1   @smoke_Test   @Test_Rol_All
                scenario: Login with different roles -- @1.2 
e                given I am on the login page ... passed in 0.9936s 
                when I enter cbarbosa@identidadtech.com and Pruebas123* ... passed in 2.604s 
                when I click the &#34;Next&#34; button ... passed in 1.26s 
                when I should be logged in successfully ... passed in 6.592s 
                when I should see my cbarbosa@identidadtech.com and CompanyAdmin displayed on the screen ... failed in 4.091s 
@scenario.end
            ----------------------------------------------------------------------------------------------------
            ]]>
            </system-out>
        </testcase><testcase time="14.929056644439697" name="Login_With_Different_Roles_--_@1.3_" status="failed"
         classname="Test_Rol_All" >
            <failure message="'global_functions' object has no attribute 'evidence_path'" type="AssertionError">
                    <![CDATA[ Failing step: when I should see my dmendez@identidadtech.com and user displayed on the screen ... failed in 4.087s  Location:4
                        {'step_type': 'when', 'name': 'I should see my dmendez@identidadtech.com and user displayed on the screen', 'text': 'None', 'status': 'failed', 'duration': 4.086862087249756, 'error_msg': "'global_functions' object has no attribute 'evidence_path'", 'error_lines': ['  File "/usr/local/lib/python3.8/dist-packages/behave/model.py", line 1329, in run\n    match.run(runner.context)\n', '  File "/usr/local/lib/python3.8/dist-packages/behave/matchers.py", line 98, in run\n    self.func(context, *args, **kwargs)\n', '  File "steps/test_rol_step.py", line 38, in test_step_impl\n    context.menu_page.verify_rol_page(rol_esperado)\n', '  File "/home/fpalencia/Automations/mientorno/test-pruebas-automatizadas/Project/tests/pages/menu_page.py", line 115, in verify_rol_page\n    self.action.attach_screenshot_to_report()\n', '  File "/home/fpalencia/Automations/mientorno/test-pruebas-automatizadas/Project/tests/pages/global_functions.py", line 184, in attach_screenshot_to_report\n    screenshot_path = os.path.join(self.evidence_path, f"{name}.png")\n'], 'hash': 89462523, 'index': 4}
                    ]]>
                </failure><system-out>
            <![CDATA[
            @scenario.begin
                @Test_Rol_All_1   @smoke_Test   @Test_Rol_All
                scenario: Login with different roles -- @1.3 
e                given I am on the login page ... passed in 0.9516s 
                when I enter dmendez@identidadtech.com and Pruebas123* ... passed in 2.625s 
                when I click the &#34;Next&#34; button ... passed in 1.258s 
                when I should be logged in successfully ... passed in 6.008s 
                when I should see my dmendez@identidadtech.com and user displayed on the screen ... failed in 4.087s 
@scenario.end
            ----------------------------------------------------------------------------------------------------
            ]]>
            </system-out>
        </testcase></testsuite>